import { useState } from "react";

const services = [
  {id:"web",icon:"🌐",title:"Web & Web App Development",desc:"Fast, accessible websites and business applications designed to convert visitors and simplify operations.",detail:"We create responsive corporate websites, customer portals, dashboards and full-scale web applications that are fast, secure and easy to manage.",deliverables:["Responsive UX and interface design","Frontend and backend development","CMS, analytics and SEO setup","Testing, deployment and support"]},
  {id:"mobile",icon:"📱",title:"Mobile App Development",desc:"Intuitive Android, iOS and cross-platform apps built around your customers and business goals.",detail:"We design and build reliable mobile experiences for Android and iOS, from customer-facing apps to workforce and field-service solutions.",deliverables:["Product discovery and app strategy","Android, iOS or cross-platform development","API and payment integration","Store launch and ongoing upgrades"]},
  {id:"custom",icon:"⚙️",title:"Custom Software Solutions",desc:"Purpose-built software that replaces manual work, connects teams and grows with your organisation.",detail:"We translate your unique workflows into secure software that improves visibility, accuracy and operational control.",deliverables:["Business process analysis","Custom architecture and development","Role-based admin and reporting","Data migration and integration"]},
  {id:"ai",icon:"🤖",title:"AI, Automation & Smart Solutions",desc:"Practical AI and workflow automation that reduce repetitive tasks and turn data into action.",detail:"We introduce useful AI and automation where it creates measurable value—without adding unnecessary complexity.",deliverables:["AI-assisted workflows and chatbots","Document and data automation","Process orchestration","Monitoring and human review controls"]},
  {id:"cloud",icon:"☁️",title:"Cloud & Digital Solutions",desc:"Secure, resilient cloud architecture, migration and modernisation for dependable digital services.",detail:"We help businesses deploy and modernise applications on scalable cloud foundations with security and reliability built in.",deliverables:["Cloud architecture and migration","Deployment pipelines and environments","Performance and security improvements","Backup, monitoring and recovery"]},
  {id:"api",icon:"🔗",title:"API & System Integration",desc:"Reliable integrations that connect payments, platforms, data and third-party services into one workflow.",detail:"We connect disconnected systems so information moves securely and teams can operate from a consistent source of truth.",deliverables:["REST API design and development","Payment and third-party integrations","Legacy system connectivity","Data synchronisation and monitoring"]},
  {id:"commerce",icon:"🛒",title:"E-commerce & Business Portals",desc:"Secure storefronts and portals with payments, inventory, customer journeys and admin control.",detail:"We build commerce and self-service platforms that simplify buying, payments, fulfilment and customer management.",deliverables:["Product catalogue and checkout","Payment gateway integration","Inventory and order workflows","Customer and admin portals"]},
  {id:"product",icon:"🧩",title:"Product Development & Implementation",desc:"From discovery and prototype to launch, we turn product ideas into production-ready solutions.",detail:"We act as an end-to-end product partner, shaping an idea, validating priorities and implementing a launch-ready digital product.",deliverables:["Discovery and product roadmap","Prototype and MVP development","Production implementation","Launch planning and iteration"]},
  {id:"support",icon:"🛟",title:"Software Support & Maintenance",desc:"Proactive monitoring, upgrades, performance improvements and responsive technical support.",detail:"We keep your software stable, secure and useful through structured maintenance, rapid issue resolution and continuous improvement.",deliverables:["Application monitoring and fixes","Security and dependency updates","Performance optimisation","Enhancements and technical support"]},
];
const clients = [
  {name:"NextGenRoboticX",url:"https://www.nextgenroboticx.com/",category:"Robotics education platform",thumb:"https://s.wordpress.com/mshots/v1/https%3A%2F%2Fwww.nextgenroboticx.com%2F?w=1200"},
  {name:"NagarikSuraksha",url:"https://www.nagariksuraksha.com/",category:"Legal education platform",thumb:"https://s.wordpress.com/mshots/v1/https%3A%2F%2Fwww.nagariksuraksha.com%2F?w=1200"},
  {name:"ConsultKaro",url:"https://www.consultkaro.org/",category:"Property consulting platform",thumb:"https://s.wordpress.com/mshots/v1/https%3A%2F%2Fwww.consultkaro.org%2F?w=1200"},
  {name:"Lekhapora Shekho",url:"https://lekhaporashekho.com/",category:"Coaching and learning platform",thumb:"https://s.wordpress.com/mshots/v1/https%3A%2F%2Flekhaporashekho.com%2F?w=1200"},
];

const industries = ["Education & EdTech", "Legal & Professional Services", "Retail & E-commerce", "Startups & SaaS", "Healthcare", "Social Impact"];
const processes = [
  {id:"discover",icon:"🔎",title:"Discover",desc:"We understand your users, goals, challenges and definition of success.",detail:"We begin by understanding the business problem, target users, current processes and the measurable outcome your solution needs to achieve.",deliverables:["Stakeholder discovery sessions","User and workflow analysis","Goals and success measures","Initial opportunity assessment"]},
  {id:"define",icon:"🗺️",title:"Define",desc:"We shape the scope, architecture, user journey and delivery roadmap.",detail:"We convert discovery findings into a practical product definition, prioritised scope and transparent implementation plan.",deliverables:["Feature priorities and scope","User journeys and requirements","Solution architecture","Timeline and delivery roadmap"]},
  {id:"design-build",icon:"🛠️",title:"Design & Build",desc:"We create, test and refine the solution through visible milestones.",detail:"Our designers and engineers work together in focused iterations, giving you regular visibility and opportunities to review progress.",deliverables:["Interface and experience design","Frontend and backend development","Integrations and data workflows","Quality assurance and security testing"]},
  {id:"launch-grow",icon:"🚀",title:"Launch & Grow",desc:"We deploy, monitor, support and evolve your product with confidence.",detail:"We prepare the product for a dependable launch, support adoption and continue improving it using real operational feedback.",deliverables:["Production deployment","Launch and adoption support","Monitoring and maintenance","Enhancements and growth roadmap"]},
];

export default function Home() { const [selectedService,setSelectedService]=useState(null); const [selectedProcess,setSelectedProcess]=useState(null); return <main>
  <header className="nav-wrap"><nav className="nav container" aria-label="Primary navigation"><a href="#top" className="brand" aria-label="Emplementer home"><img src="/logo-emplementer.png" alt="Emplementer software development and solution provider" /></a><div className="nav-links"><div className="services-menu"><a href="#services" className="services-trigger">Services <span>⌄</span></a><div className="services-dropdown" aria-label="Services menu">{services.map(service=><a key={service.id} href={`#service-${service.id}`}><span>{service.icon}</span>{service.title}</a>)}</div></div><a href="#about">About</a><a href="#clients">Our Clients</a><div className="process-menu"><a href="#process" className="process-trigger">Process <span>⌄</span></a><div className="process-dropdown" aria-label="Process menu">{processes.map(process=><a key={process.id} href={`#process-${process.id}`}><span>{process.icon}</span><b>{process.title}</b><small>{process.desc}</small></a>)}</div></div><a href="#contact" className="nav-cta">Start a project</a></div></nav></header>
  <section id="top" className="split-hero" aria-labelledby="hero-title"><div className="container split-hero-inner"><div className="split-hero-copy"><p className="eyebrow">Software development & solution provider</p><h1 id="hero-title">We implement <span>ideas to reality.</span></h1><p>Emplementer turns your vision into secure, scalable and user-friendly digital products—from strategy and design to development, launch and support.</p><div className="hero-actions"><a className="button primary" href="#contact">Discuss your idea <span>↗</span></a><a className="button secondary" href="#services">Explore services</a></div><div className="trust-row"><span>Strategy</span><i>•</i><span>Design</span><i>•</i><span>Development</span><i>•</i><span>Implementation</span></div></div><div className="split-hero-visual" role="img" aria-label="Idea to reality digital product development"><img src="/right-plane-banner-v6.jpg" width="1145" height="804" decoding="async" fetchPriority="high" alt="" /></div></div></section>
  <section className="intro" id="about"><div className="container split"><div><p className="section-label">Your end-to-end technology partner</p><h2>More than code.<br/>A solution that works.</h2></div><div className="intro-copy"><p>Great software begins with a clear understanding of the real problem. We collaborate with founders, businesses and organisations to shape the right solution—then design, build and implement it with care.</p><p>Whether you need a first digital product or want to modernise an established system, we bring together product thinking, engineering and dependable delivery.</p></div></div><div className="container proof-grid"><article><strong>End-to-end</strong><span>From idea and planning to launch and support</span></article><article><strong>Built to scale</strong><span>Reliable foundations for long-term growth</span></article><article><strong>User-first</strong><span>Simple experiences people enjoy using</span></article><article><strong>Transparent</strong><span>Clear communication at every milestone</span></article></div></section>
  <section id="services" className="services-section"><div className="container section-head"><div><p className="section-label">What we build</p><h2>Digital solutions with<br/><em>real impact.</em></h2></div><p>Focused technology services for every stage of your digital journey.</p></div><div className="container services-grid">{services.map(service => <article id={`service-${service.id}`} className="service-card" key={service.id}><div className="service-icon" aria-hidden="true">{service.icon}</div><h3>{service.title}</h3><p>{service.desc}</p><button type="button" onClick={()=>setSelectedService(service)} aria-label={`Know more about ${service.title}`}>Know More <span>↗</span></button></article>)}</div></section>
  <section id="clients" className="clients-section"><div className="container section-head"><div><p className="section-label">Our clients</p><h2>Digital experiences<br/><em>we have created.</em></h2></div><p>Explore selected websites and platforms designed and developed by Emplementer.</p></div><div className="container clients-grid">{clients.map(client=><a className="client-card" key={client.name} href={client.url} target="_blank" rel="noopener noreferrer" aria-label={`Visit ${client.name} website`}><div className="client-preview"><img src={client.thumb} alt={`${client.name} website landing page`} loading="lazy" width="1200" height="675"/></div><div className="client-meta"><span><strong>{client.name}</strong><small>{client.category}</small></span><i aria-hidden="true">↗</i></div></a>)}</div></section>
  <section className="industries"><div className="container"><p className="section-label">Industry experience</p><h2>Technology shaped around<br/>your world.</h2><div className="industry-list">{industries.map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div></div></section>
  <section id="process" className="process"><div className="container section-head"><div><p className="section-label">How we work</p><h2>A clear path from<br/><em>concept to launch.</em></h2></div><p>Collaborative, practical and focused on measurable outcomes.</p></div><div className="container process-grid">{processes.map(process=><article id={`process-${process.id}`} key={process.id}><div className="process-icon" aria-hidden="true">{process.icon}</div><h3>{process.title}</h3><p>{process.desc}</p><button type="button" onClick={()=>setSelectedProcess(process)}>Know More <span>↗</span></button></article>)}</div></section>
  <section className="why"><div className="container split"><div><p className="section-label">Why Emplementer</p><h2>We treat your idea<br/>like a product—not<br/>just a project.</h2></div><div className="why-list"><div><b>01</b><span><strong>Business-first thinking</strong><small>Technology decisions grounded in your real goals.</small></span></div><div><b>02</b><span><strong>One accountable partner</strong><small>A connected team from discovery through maintenance.</small></span></div><div><b>03</b><span><strong>Quality without complexity</strong><small>Clean, secure solutions that remain easy to operate.</small></span></div><div><b>04</b><span><strong>Partnership that continues</strong><small>Support and improvement long after launch day.</small></span></div></div></div></section>
  <section className="faq"><div className="container"><p className="section-label">Frequently asked questions</p><h2>Before we get started.</h2><div className="faq-grid"><details><summary>What types of projects do you take on?</summary><p>We build websites, web and mobile applications, custom software, portals, e-commerce platforms, AI automation and system integrations.</p></details><details><summary>Can you build from an early-stage idea?</summary><p>Yes. We help clarify requirements, prioritise features and create a realistic roadmap before design and development begin.</p></details><details><summary>Do you support products after launch?</summary><p>Yes. We offer maintenance, monitoring, performance improvement, feature development and ongoing technical support.</p></details><details><summary>How do I receive a project estimate?</summary><p>Share your idea, current challenge and desired outcome. After a discovery conversation, we provide a proposed scope, timeline and cost estimate.</p></details></div></div></section>
  <section id="contact" className="contact"><div className="container contact-inner"><p className="section-label">Have an idea?</p><h2>Let’s turn it into<br/><span>something real.</span></h2><p>Tell us what you want to build. We’ll help you find the clearest path from idea to implementation.</p><a className="button primary" href="https://wa.me/919830015487?text=Hello%20Emplementer%2C%20I%20would%20like%20to%20discuss%20a%20software%20project." target="_blank" rel="noopener noreferrer">Chat on WhatsApp <span>↗</span></a></div></section>
  {selectedService&&<div className="service-modal-backdrop" role="presentation" onClick={()=>setSelectedService(null)}><section className="service-modal" role="dialog" aria-modal="true" aria-labelledby="service-modal-title" onClick={e=>e.stopPropagation()}><button className="modal-close" type="button" onClick={()=>setSelectedService(null)} aria-label="Close service details">×</button><div className="modal-icon" aria-hidden="true">{selectedService.icon}</div><p className="section-label">Our service</p><h2 id="service-modal-title">{selectedService.title}</h2><p>{selectedService.detail}</p><h3>What we can deliver</h3><ul>{selectedService.deliverables.map(item=><li key={item}>{item}</li>)}</ul><a className="button primary" href={`mailto:contact@emplementer.com?subject=${encodeURIComponent(selectedService.title)} enquiry`} onClick={()=>setSelectedService(null)}>Discuss this service <span>↗</span></a></section></div>}
  {selectedProcess&&<div className="service-modal-backdrop" role="presentation" onClick={()=>setSelectedProcess(null)}><section className="service-modal" role="dialog" aria-modal="true" aria-labelledby="process-modal-title" onClick={e=>e.stopPropagation()}><button className="modal-close" type="button" onClick={()=>setSelectedProcess(null)} aria-label="Close process details">×</button><div className="modal-icon" aria-hidden="true">{selectedProcess.icon}</div><p className="section-label">How we work</p><h2 id="process-modal-title">{selectedProcess.title}</h2><p>{selectedProcess.detail}</p><h3>What happens at this stage</h3><ul>{selectedProcess.deliverables.map(item=><li key={item}>{item}</li>)}</ul><a className="button primary" href="#contact" onClick={()=>setSelectedProcess(null)}>Start your project <span>↗</span></a></section></div>}
  <footer><div className="container footer-top"><img src="/logo-emplementer.png" alt="Emplementer"/><p>We code. We build.<br/><span>We implement.</span></p></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Emplementer. All rights reserved.</span><div><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a></div></div></footer>
</main> }
